baseURL = "https://pixelabswedia-cloud.github.io/Blog/"
languageCode = "id-id"
title = "Tech Insights Daily"

[params]
    description = "Latest updates on AI, Technology, and Digital Trends."
    author = "Saka Editorial"
